"""Initial migration

Revision ID: 9aab907913a6
Revises: 
Create Date: 2023-11-25 22:11:22.080644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aab907913a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_url', sa.String(length=250), nullable=False),
    sa.Column('img_url', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('has_sockets', sa.String(length=250), nullable=False),
    sa.Column('has_toilet', sa.String(length=250), nullable=False),
    sa.Column('wifi', sa.String(length=250), nullable=False),
    sa.Column('can_take_calls', sa.String(length=250), nullable=False),
    sa.Column('seats', sa.String(length=250), nullable=False),
    sa.Column('coffe_price', sa.String(length=250), nullable=False),
    sa.Column('add_button', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe')
    # ### end Alembic commands ###
